site_name: DbC Library
theme: readthedocs
repo_url: https://github.com/FIUNER-LICA/biblioteca-dbc-cpp
repo_name: 'biblioteca-dbc'
edit_uri: null
nav:
  - Home: index.md 
  - API-Reference: apireference.md
